n = int(input('Digite um número para ver sua Tabuada: '))
print('-'*12)
print(f'{n} x  1 = {n*1:2}')
print(f'{n} x  2 = {n*2:2}')
print(f'{n} x  3 = {n*3:2}')
print(f'{n} x  4 = {n*4:2}')
print(f'{n} x  5 = {n*5:2}')
print(f'{n} x  6 = {n*6:2}')
print(f'{n} x  7 = {n*8:2}')
print(f'{n} x  9 = {n*9:2}')
print(f'{n} x 10 = {n*10:2}')
print('-'*12)
